[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
solc_version = "0.8.17"
evm_version = "london"
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
# use_literal_content = true
auto_detect_remappings = false

[rpc_endpoints]
avalanche = "https://rpc.ankr.com/avalanche"
gnosis = "https://rpc.ankr.com/gnosis"
bsc = "https://rpc.ankr.com/bsc"
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
goerli = "https://rpc.ankr.com/eth_goerli"
sepolia = "https://rpc.ankr.com/eth_sepolia"
koi = "https://koi-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"
darwinia = "https://rpc.darwinia.network"
arbitrum = "https://arb1.arbitrum.io/rpc"
polygon = "https://polygon-rpc.com"
ethereum = "https://mainnet.infura.io/v3/${INFURA_KEY}"
mantle = "https://rpc.mantle.xyz"
blast = "https://rpc.blast.io"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"
base = "https://mainnet.base.org"
base-sepolia = "https://sepolia.base.org"
scroll = "https://rpc.scroll.io"
moonbeam = "https://rpc.api.moonbeam.network"
linea = "https://1rpc.io/linea"
astar = "https://rpc.startale.com/astar-zkevm"
zircuit = "https://zircuit1-mainnet.p2pify.com"
morph = "https://rpc.morphl2.io"

[etherscan]
blast = { key = "${ETHERSCAN_BLAST_KEY}", url = "https://api.blastscan.io/api"}
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}" }
arbitrum = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-goerli = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
darwinia = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://darwinia.api.subscan.io/api/scan/evm/contract/verifysource" }
koi = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://koi-scan.darwinia.network/api" }
crab = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://crab.api.subscan.io/api/scan/evm/contract/verifysource" }
optimism = { key = "${ETHERSCAN_OPTIMISM_KEY}" }
base = { key = "${ETHERSCAN_BASE_KEY}" }
base-sepolia = { key = "${ETHERSCAN_BASE_KEY}" }
astar = { key = "${ETHERSCAN_API_KEY}"}
morph = { key = "xxx", url = "https://explorer.morphl2.io/api", chain = 2818}
